language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

dist: xenial

install:
    - pip install -U pip
    # TODO: Use pyro release version when available
    - pip install git+https://github.com/pyro-ppl/pyro/pyro.get@dev
    - pip install -e .
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - stage: unit
          name: "unit tests"
          python: 3.6
          script:
              - pytest -vs --tb=short
